### ISSUE TITLE
Missing timestep in trajectory?

### ISSUE THREAD

**Issue by leifdenby** [EUREC4A-UK/lagtraj#151]
@sjboeing just mentioned to me that there might be an issue with a timestep missing in the trajectory output.

If we have a yaml-file file for a trajectory with the following:

```yaml
datetime_origin: 2020-01-01T12:15
forward_duration: PT3H
backward_duration: None
timestep: PT1H
...
```

The trajectory should contain the following times (and only these):

```
2020-01-01T12:15
2020-01-01T13:15
2020-01-01T14:15
2020-01-01T15:15
```

but may currently be missing the last one. Is that correct @sjboeing?
