### ISSUE TITLE
Optimising era5 data loading (creating trajectories)

### ISSUE THREAD

**Issue by leifdenby** [EUREC4A-UK/lagtraj#32]
This is just for some notes for my own future reference to track the improvements in speed.

For the testing I am using trajectory setup `eurec4a_20191209_12_lag`:

```yaml
trajectory_type : lagrangian
velocity_method : single_height_level
velocity_method_height: 700.
domain          : lagtraj://eurec4a_circle_eul
lat_origin      : 13.3
lon_origin      : -57.717
datetime_origin : "2020-01-03T12:00"
backward_duration : PT12H
forward_duration : PT12H
timestep        : domain_data  # or for example PT1H
```
